### PR TITLE
feat: consider files field from package.json

### PR DESCRIPTION
**Pull request by shmidt-i**
Implements #10, more info in the issue

### CODE REVIEW

**Comment by shmidt-i** [comment]
Hey @azz, could you please give a look when you have time?

**Review by azz — APPROVED** [review]

**Comment by benjdlambert** [comment]
@azz would it be possible for you to bump and release this change?

**Comment by azz** [comment]
Oh usually semantic release does this. Maybe the Travis pipes are clogged.

**Comment by azz** [comment]
Tokens needed to be rotated.

**Comment by azz** [comment]
Job is queued - https://travis-ci.org/github/azz/eslint-plugin-monorepo/jobs/739409747

**Comment by azz** [comment]
Not sure why queuing is taking so long. Just bumped to newer Node.js version. New job - https://travis-ci.org/github/azz/eslint-plugin-monorepo/jobs/739483997

**Comment by azz** [comment]
Looks like Travis is just super under load.

https://www.traviscistatus.com/#month

image

Gotta duck out now, but ping me if the job doesn't publish the package.

**Comment by benjdlambert** [comment]
@azz yep seems that way, thanks for having an eye on it. guessing it's gonna fix itself to be honest. also if i worked at travis, i'd be pretty concerned at the state of that graph 😂

**Comment by azz** [comment]
https://github.com/azz/eslint-plugin-monorepo/releases/tag/v0.3.0

**Pull request merged**
